---
ID: "bbe44e92-6c80-43ed-82f0-58b583a60424"
Parent: "d1850b59-d54c-41da-9e05-e712f05262b1"
Template: "d1850b59-d54c-41da-9e05-e712f05262b1"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Allianz Home Hero/Allianz Home Hero/__Standard Values"
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260614T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bbe44e92-6c80-43ed-82f0-58b583a60424"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260614T120000Z
    - ID: "6e9d561f-9692-48e7-a720-d10f4f379fca"
      Hint: Title
      Value: "Allianz annuities insurance: for all that's ahead"
    - ID: "52ff2838-9529-415a-bdaf-303f771256c5"
      Hint: Copy
      Value: |
        <p>For more than 125 years, Allianz Life Insurance Company of North America (Allianz) has been helping Americans like you prepare for their financial future.</p>
